In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("/content/wcer.csv")

df.head()

,STORE,UPC,WEEK,MOVE,QTY,PRICE,SALE,PROFIT,OK,PRICE_HEX,PROFIT_HEX
0,51,317,372,1.0,1.0,26.02,NaN,62.52,1.0,403A051EB851EB85,404F428F5C28F5C3
1,51,317,373,0.0,1.0,0.00,NaN,0.00,1.0,0000000000000000,0000000000000000
2,51,317,374,0.0,1.0,0.00,NaN,0.00,1.0,0000000000000000,0000000000000000
3,51,317,375,0.0,1.0,0.00,NaN,0.00,1.0,0000000000000000,0000000000000000
4,51,317,376,0.0,1.0,0.00,NaN,0.00,1.0,0000000000000000,0000000000000000

In [10]:
df.shape

(968458, 11)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 968458 entries, 0 to 968457
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   STORE       968458 non-null  int64
 1   UPC         968458 non-null  int64
 2   WEEK        968458 non-null  int64
 3   MOVE        968457 non-null  float64
 4   QTY         968457 non-null  float64
 5   PRICE       968457 non-null  float64
 6   SALE        39577 non-null   object
 7   PROFIT      968457 non-null  float64
 8   OK          968457 non-null  float64
 9   PRICE_HEX   968457 non-null  object
 10  PROFIT_HEX  968457 non-null  object
dtypes: float64(5), int64(3), object(3)
memory usage: 81.3+ MB

In [ ]:
df.describe()

,STORE,UPC,WEEK,MOVE,QTY,PRICE,PROFIT,OK
count,6.602582e+06,6.602582e+06,6.602582e+06,6.602582e+06,6.602582e+06,6.602582e+06,6.602582e+06,6.602582e+06
mean,8.322369e+01,3.663620e+09,1.955693e+02,1.408119e+01,1.001201e+00,2.241151e+00,1.252218e+01,9.786016e-01
std,3.648211e+01,7.243855e+09,1.167867e+02,5.058522e+01,4.929841e-02,1.541937e+00,1.143999e+01,1.447085e-01
min,2.000000e+00,3.170000e+02,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,-9.969000e+01,0.000000e+00
25%,5.600000e+01,1.600069e+09,9.600000e+01,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
50%,8.900000e+01,3.800000e+09,1.890000e+02,8.000000e+00,1.000000e+00,2.790000e+00,1.374000e+01,1.000000e+00
75%,1.130000e+02,3.800013e+09,3.110000e+02,1.700000e+01,1.000000e+00,3.390000e+00,1.861000e+01,1.000000e+00
max,1.460000e+02,7.916692e+10,3.990000e+02,1.868800e+04,4.000000e+00,2.602000e+01,9.999000e+01,1.000000e+00

In [ ]:
df.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
6602577    False
6602578    False
6602579    False
6602580    False
6602581    False
Length: 6602582, dtype: bool

In [ ]:
duplicates = df.duplicated().sum()
print("Total duplicate rows:",duplicates)
df = df.drop_duplicates()
print("Duplicate rows removed.Total rows now:",len(df))

Total duplicate rows: 0
Duplicate rows removed.Total rows now: 6602582

In [ ]:
df.shape

(6602582, 11)

In [12]:

df.isnull().sum()

STORE              0
UPC                0
WEEK               0
MOVE               1
QTY                1
PRICE              1
SALE          928881
PROFIT             1
OK                 1
PRICE_HEX          1
PROFIT_HEX         1
dtype: int64

In [13]:
print(df["SALE"].dtype)
print(df["SALE"].dropna().head(10))

object
62     L
271    B
272    B
274    B
288    B
290    B
291    B
312    B
363    B
376    B
Name: SALE, dtype: object

In [14]:
df["SALE"].value_counts(dropna=False)

SALE
NaN    928881
B       26139
S       10937
G        1910
C         590
L           1
Name: count, dtype: int64

In [15]:
print("SALE unique values:")
print(df["SALE"].unique())

print("\nOK unique values:")
print(df["OK"].unique())

SALE unique values:
[nan 'L' 'B' 'S' 'G' 'C']

OK unique values:
[ 1.  0. nan]